{{- if .Values.speechMcp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.speechMcp.name }}-sa
  labels:
    category: cobol-modernization
    app.kubernetes.io/component: speech-mcp
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
