{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mcp-inspector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-inspector.labels" . | nindent 4 }}
    {{- with .Values.global.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    - "mcp-inspector.{{ .Release.Namespace }}.127.0.0.1.nip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "mcp-inspector.fullname" . }}
          port: {{ .Values.service.clientPort }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mcp-inspector.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-inspector.labels" . | nindent 4 }}
    {{- with .Values.global.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    - "mcp-inspector-proxy.{{ .Release.Namespace }}.127.0.0.1.nip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "mcp-inspector.fullname" . }}
          port: {{ .Values.service.proxyPort }}
{{- end }}
