apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-inspector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-inspector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.clientPort }}
    targetPort: client
    protocol: TCP
    name: client
  - port: {{ .Values.service.proxyPort }}
    targetPort: proxy
    protocol: TCP
    name: proxy
  selector:
    {{- include "mcp-inspector.selectorLabels" . | nindent 4 }}
