{{- if .Values.argoWorkflows.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-default-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ark-tenant-role
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo-workflows
{{- end }}
