{{- if .Values.versitygw.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "file-gateway.s3SecretName" . }}
  labels:
    {{- include "file-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: versitygw
type: Opaque
data:
  access-key-id: {{ .Values.versitygw.s3Credentials.accessKeyId | b64enc | quote }}
  secret-access-key: {{ include "file-gateway.s3SecretAccessKey" . | b64enc | quote }}
{{- end }}
