{{- if .Values.versitygw.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "file-gateway.fullname" . }}-versitygw
  labels:
    {{- include "file-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: versitygw
spec:
  type: {{ .Values.versitygw.service.type }}
  ports:
  - port: {{ .Values.versitygw.service.port }}
    targetPort: s3
    protocol: TCP
    name: s3
  selector:
    {{- include "file-gateway.versitygw.selectorLabels" . | nindent 4 }}
{{- end }}
