{{- if and .Values.versitygw.enabled .Values.versitygw.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "file-gateway.versitygw.serviceAccountName" . }}
  labels:
    {{- include "file-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: versitygw
{{- end }}
