apiVersion: v1
kind: ServiceAccount
metadata:
  name: noah-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: noah
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: noah-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: noah
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: noah-admin-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: noah
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: noah-admin
subjects:
- kind: ServiceAccount
  name: noah-sa
  namespace: {{ .Release.Namespace }}